import React from "react";
import { Link } from "wouter";
import { Briefcase, Link2, Layers, CalendarCheck, BookOpen, ArrowRight } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useListJobApplications, useListHabits, useListEvents } from "@workspace/api-client-react";

export default function Dashboard() {
  const { data: jobs } = useListJobApplications();
  const { data: habits } = useListHabits();
  const { data: events } = useListEvents();

  const apps = [
    {
      title: "Job Tracker",
      description: "Manage your career search and track applications.",
      icon: Briefcase,
      color: "bg-blue-500",
      href: "/jobs",
      stat: jobs ? `${jobs.length} Applications` : "Loading...",
    },
    {
      title: "Habit Chain",
      description: "Build lasting routines with daily tracking.",
      icon: Layers,
      color: "bg-emerald-500",
      href: "/habits",
      stat: habits ? `${habits.length} Habits` : "Loading...",
    },
    {
      title: "Event Board",
      description: "Plan and organize upcoming events and RSVPs.",
      icon: CalendarCheck,
      color: "bg-orange-500",
      href: "/events",
      stat: events ? `${events.length} Events` : "Loading...",
    },
    {
      title: "Link Vault",
      description: "Save and categorize important bookmarks.",
      icon: Link2,
      color: "bg-purple-500",
      href: "/links",
      stat: "Access Vault",
    },
    {
      title: "Study Deck",
      description: "Master new skills with spaced repetition flashcards.",
      icon: BookOpen,
      color: "bg-pink-500",
      href: "/flashcards",
      stat: "Start Studying",
    }
  ];

  return (
    <div className="p-6 lg:p-10 max-w-7xl mx-auto space-y-8">
      <div className="relative rounded-3xl overflow-hidden bg-primary/5 border border-primary/10 p-8 lg:p-12">
        <div className="relative z-10 max-w-2xl">
          <h1 className="text-4xl lg:text-5xl font-display font-bold text-foreground mb-4 leading-tight">
            Welcome to your <br/><span className="text-primary">Productivity Hub</span>
          </h1>
          <p className="text-lg text-muted-foreground mb-8">
            All your essential tools in one unified workspace. Track jobs, build habits, save resources, and learn faster.
          </p>
          <div className="flex gap-4">
            <Link href="/jobs">
              <Button size="lg" className="rounded-xl shadow-lg shadow-primary/20 hover:shadow-xl hover:-translate-y-0.5 transition-all">
                Go to Job Tracker <ArrowRight className="ml-2 w-4 h-4" />
              </Button>
            </Link>
          </div>
        </div>
        {/* Decorative background image generated by AI */}
        <div className="absolute top-0 right-0 bottom-0 w-1/2 opacity-30 pointer-events-none mix-blend-multiply dark:mix-blend-screen">
            <img 
              src={`${import.meta.env.BASE_URL}images/dashboard-hero.png`} 
              alt="Decorative background" 
              className="w-full h-full object-cover object-left [mask-image:linear-gradient(to_right,transparent,black)]"
            />
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-display font-bold mb-6">Your Applications</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {apps.map((app) => (
            <Link key={app.title} href={app.href} className="group block">
              <Card className="h-full hover:shadow-xl hover:border-primary/30 transition-all duration-300 rounded-2xl overflow-hidden bg-card/50 backdrop-blur-sm">
                <CardHeader className="pb-4">
                  <div className="flex justify-between items-start">
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-white ${app.color} shadow-lg shadow-black/10 group-hover:scale-110 transition-transform duration-300`}>
                      <app.icon className="w-6 h-6" />
                    </div>
                    <ArrowRight className="w-5 h-5 text-muted-foreground opacity-0 group-hover:opacity-100 group-hover:translate-x-1 transition-all" />
                  </div>
                  <CardTitle className="mt-4 text-xl">{app.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground mb-4">{app.description}</p>
                  <div className="inline-flex items-center px-3 py-1 rounded-full bg-secondary text-xs font-medium text-secondary-foreground">
                    {app.stat}
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
